### ISSUE TITLE
【译】GraphQL 初学者指南

### ISSUE THREAD

**Issue by Aemple** [FreeCodeCamp-Chengdu/IT-Technology-weekly#55]
GraphQL 是当代构建 API 的最佳方式，本文将阐述为什么你应该开始学习 GraphQL，让你了解 GraphQL 的工作原理，以及如何使用 GraphQL 创建设计精良、高效并且功能强大的 API。
你可能已经听说过 GraphQL，因为很多开发者和公司都在使用它。由于 GraphQL 是开源的，所以社区也是很庞大的存在。让我们在实践中学习 GraphQL 的工作原理，领略它的魔力了。
链接：https://juejin.im/post/5c32119651882525a50bb436

**Comment by FengShangWuQi** [comment]
You’ve probably already heard about GraphQL, as a lot of people and companies are using it. Since GraphQL is open-source, its community has grown huge.

Now, it’s time for you start to learn in practice how GraphQL works and all about its magic.

你可能已经听说过 GraphQL，因为很多开发者和公司都在使用它。由于 GraphQL 是开源的，所以社区也是很庞大的存在。让我们在实践中学习 GraphQL 的工作原理，领略它的魔力了。

文章翻译不是很成熟，周刊收录的译文建议推荐有热度且翻译成熟的文章。
